[project]
name = "xrp-wallet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "click>=8.1.8",
    "cryptography>=44.0.2",
    "xrpl-py>=4.1.0",
]
